---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lab0-jupyter-cm
  namespace: jgorev-370834

data:
  jupyter_notebook_config.py: |
    c.NotebookApp.trust_xheaders = True
    c.NotebookApp.quit_button = False